import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, Download, Mail, Copy, FileText } from "lucide-react";

export const Route = createFileRoute("/reports")({
  head: () => ({ meta: [{ title: "Reports — CampusPM AI" }] }),
  component: ReportsPage,
});

function ReportsPage() {
  return (
    <AppShell>
      <div className="p-6 lg:p-8 space-y-6 max-w-[1400px] mx-auto">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Executive Reports</h1>
            <p className="text-sm text-muted-foreground">
              AI-drafted leadership updates ready for distribution.
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="gap-1.5"><Copy className="h-4 w-4" /> Copy</Button>
            <Button variant="outline" size="sm" className="gap-1.5"><Mail className="h-4 w-4" /> Email</Button>
            <Button variant="outline" size="sm" className="gap-1.5"><Download className="h-4 w-4" /> PDF</Button>
            <Button size="sm" className="gap-1.5"><Sparkles className="h-4 w-4" /> Regenerate</Button>
          </div>
        </div>

        <Card className="shadow-elevated">
          <CardHeader className="border-b border-border">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-lg">Weekly Executive Status — Week of May 18</CardTitle>
                <p className="mt-1 text-xs text-muted-foreground">
                  Generated by CampusPM AI · Reviewed by Elena Marsh · Ready to send
                </p>
              </div>
              <FileText className="h-5 w-5 text-muted-foreground" />
            </div>
          </CardHeader>
          <CardContent className="p-8 space-y-6 max-w-3xl">
            <section>
              <h3 className="text-sm font-semibold text-primary uppercase tracking-wider">Leadership summary</h3>
              <p className="mt-2 text-sm leading-relaxed text-foreground/90">
                The portfolio remains directionally healthy with portfolio health trending up to 81 (W8) from 71 (W1).
                Two initiatives — Digital Admissions Workflow and Campus WiFi Expansion — require executive attention
                this week due to procurement and approval bottlenecks. The AI Student Support Initiative is on track
                for its undergraduate rollout next week, with pilot satisfaction at 4.6/5.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-semibold text-primary uppercase tracking-wider">Project progress</h3>
              <ul className="mt-2 space-y-1.5 text-sm">
                <li>• <strong>AI Student Support</strong> — 82% complete, launching to all undergrads Jun 12.</li>
                <li>• <strong>Student Portal Upgrade</strong> — 68% complete, pilot beta released to 3 colleges.</li>
                <li>• <strong>Faculty Research Mgmt</strong> — 55% complete, UAT scheduled with Sciences.</li>
                <li>• <strong>Library Discovery</strong> — 49% complete, federated search integration in progress.</li>
              </ul>
            </section>

            <section>
              <h3 className="text-sm font-semibold text-destructive uppercase tracking-wider">Risks & issues</h3>
              <ul className="mt-2 space-y-1.5 text-sm">
                <li>• <strong>Digital Admissions</strong>: registrar approval bottleneck (5 packets &gt;9 days). Recommend escalation.</li>
                <li>• <strong>Campus WiFi</strong>: vendor SLA risk; Phase 2 hardware delayed two weeks.</li>
                <li>• <strong>Research Mgmt</strong>: IRB integration scope unowned across 4 recent discussions.</li>
              </ul>
            </section>

            <section>
              <h3 className="text-sm font-semibold text-warning-foreground uppercase tracking-wider">Budget concerns</h3>
              <p className="mt-2 text-sm leading-relaxed text-foreground/90">
                Campus WiFi alternative SKU adds 8% premium ($96K) but preserves Q3 timeline.
                Decision requested by Friday to avoid budget rollover.
              </p>
            </section>

            <section>
              <h3 className="text-sm font-semibold text-success uppercase tracking-wider">Next week priorities</h3>
              <ol className="mt-2 space-y-1.5 text-sm list-decimal pl-5">
                <li>Resolve Admissions registrar approval queue with provost office.</li>
                <li>Confirm WiFi vendor decision and revise PO.</li>
                <li>Launch AI Student Support to undergrad population.</li>
                <li>Kick off Research Mgmt UAT with School of Sciences.</li>
              </ol>
            </section>
          </CardContent>
        </Card>
      </div>
    </AppShell>
  );
}
