/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'

const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stakeholders': typeof StakeholdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stakeholders': typeof StakeholdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stakeholders': typeof StakeholdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/stakeholders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/stakeholders'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/stakeholders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StakeholdersRoute: typeof StakeholdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StakeholdersRoute: StakeholdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
